#!/usr/bin/env python3
"""
Generate tnt.datasyms.toml — the game's DATA / variable symbols — from the
chris-gilmore/tnt-splat `symbol_addrs.txt` files.

This is the data-symbol counterpart to gen_syms.py (which produced the FUNCTION
map tnt.syms.toml). It's a one-time bootstrap: tnt-splat is an external project
(not vendored); clone it next to this repo (or pass --splat) and run this once.

The output is in the N64Recomp reference-symbol-file format used by RecompModTool's
`data_reference_syms_files`, so mods can refer to game variables BY NAME (e.g. the
wonders threshold table `D_800CF928`) instead of raw addresses.

Usage:
    python3 tools/gen_datasyms.py [--splat PATH_TO_tnt-splat] [-o tnt.datasyms.toml]
"""
import argparse
import re
import sys
from pathlib import Path

# NAME = 0xVRAM; // ...comment...
LINE_RE = re.compile(r"^\s*([A-Za-z_]\w*)\s*=\s*(0x[0-9A-Fa-f]+)\s*;\s*(//.*)?$")


def parse_data_symbols(path: Path):
    """Yield (name, vram) for every non-function symbol in a splat symbol_addrs file."""
    for line in path.read_text().splitlines():
        m = LINE_RE.match(line)
        if not m:
            continue
        name, vram_s, comment = m.group(1), m.group(2), (m.group(3) or "")
        # Functions carry `type:func`; everything else (typed vars, data/rodata/bss,
        # and untyped D_ globals with a size/array note) is data we want.
        if re.search(r"type:\s*func\b", comment):
            continue
        yield name, int(vram_s, 16)


# Entries already in an output file: { name = "X", vram = 0xY },
EXISTING_RE = re.compile(r'{\s*name\s*=\s*"([^"]+)"\s*,\s*vram\s*=\s*(0x[0-9A-Fa-f]+)\s*}')


def parse_existing(path: Path):
    """Return the list of (name, vram) already committed, preserving order."""
    if not path.exists():
        return []
    return [(m.group(1), int(m.group(2), 16)) for m in EXISTING_RE.finditer(path.read_text())]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--splat", default="tnt-splat",
                    help="path to a chris-gilmore/tnt-splat checkout")
    ap.add_argument("-o", "--out", default="tnt.datasyms.toml")
    ap.add_argument("--fresh", action="store_true",
                    help="regenerate from scratch, discarding any names in the existing file "
                         "(DANGEROUS: can rename symbols out from under already-written mod SOURCE)")
    args = ap.parse_args()

    splat = Path(args.splat)
    files = [splat / "symbol_addrs.txt", splat / "libultra-symbol_addrs.txt"]
    files = [f for f in files if f.exists()]
    if not files:
        sys.exit(f"error: no symbol_addrs.txt under {splat} (clone chris-gilmore/tnt-splat)")

    seen = {}
    for f in files:
        for name, vram in parse_data_symbols(f):
            seen.setdefault(vram, name)  # first name wins; game syms before libultra

    out = Path(args.out)

    # Merge-by-default: preserve every entry already in the committed file (names the
    # team may have improved/aliased are the stable contract mods reference), and only
    # APPEND ripped symbols at addresses not already present. This keeps re-ripping
    # from an updated tnt-splat non-breaking. --fresh opts out.
    kept, kept_addrs, added = [], set(), 0
    if not args.fresh:
        for name, vram in parse_existing(out):
            kept.append((vram, name))
            kept_addrs.add(vram)
    for vram, name in sorted(seen.items()):
        if vram not in kept_addrs:
            kept.append((vram, name))
            kept_addrs.add(vram)
            added += 1
    syms = sorted(kept)  # by vram
    print(f"merge: kept {len(kept) - added} existing, appended {added} new"
          if not args.fresh else f"fresh: {len(syms)} symbols")
    with out.open("w") as w:
        w.write("# Data / variable symbols for The New T64ris.\n")
        w.write("# Auto-generated by tools/gen_datasyms.py from chris-gilmore/tnt-splat\n")
        w.write("# symbol_addrs.txt. Format: N64Recomp reference-symbol file, usable as a\n")
        w.write("# mod `data_reference_syms_files` entry so mods can name game variables.\n")
        w.write("[[section]]\n")
        w.write('name = "tnt_data"\n')
        w.write("vram = 0x80000000\n")
        w.write("size = 0x00800000\n\n")  # covers 8 MB RDRAM
        w.write("symbols = [\n")
        for vram, name in syms:
            w.write(f'    {{ name = "{name}", vram = 0x{vram:08X} }},\n')
        w.write("]\n")

    print(f"wrote {out} with {len(syms)} data symbols from {', '.join(f.name for f in files)}")


if __name__ == "__main__":
    main()
