#!/usr/bin/env python3
"""Regenerate FUNCTION_INDEX.md from tnt.syms.toml + the static call graph.

Groups functions by subsystem (name prefix before the first '_'), sorted by
address within each group. `calls` = static out-degree (how many distinct
functions it calls), computed by reusing callgraph.py's edge detection. `*` after
the address marks a function that has a recompiled C body in RecompiledFuncs/**.

Usage: tools/gen_function_index.py  [> FUNCTION_INDEX.md]
Run after any rename/reorg so the navigation index stays current.
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import callgraph  # reuse build() + DEF/CALL regexes

ROOT = Path(__file__).resolve().parent.parent
SYMS = ROOT / "tnt.syms.toml"
ENTRY_RE = re.compile(r'name = "([^"]+)", vram = (0x[0-9A-Fa-f]+), size = (0x[0-9A-Fa-f]+)')


def main():
    home, callees, _callers = callgraph.build()
    defined = set(home.keys())  # functions with a recompiled C body

    funcs = []  # (name, vram, size)
    total = 0
    for line in SYMS.read_text().splitlines():
        m = ENTRY_RE.search(line)
        if not m:
            continue
        total += 1
        funcs.append((m.group(1), int(m.group(2), 16), int(m.group(3), 16)))

    groups = {}
    for name, vram, size in funcs:
        prefix = name.split("_", 1)[0]
        groups.setdefault(prefix, []).append((name, vram, size))

    out = []
    out.append("# The New T64ris — function index\n")
    out.append(
        f"Auto-generated by `tools/gen_function_index.py` from `tnt.syms.toml` "
        f"({total} symbols). Grouped by subsystem (prefix before the first `_`).\n"
        "`calls` = how many other functions this one calls (its out-degree) — "
        "**high = orchestrator, 0 = leaf/helper**.\n"
        "Sorted within each group by address. `*` after the address = has a "
        "recompiled C body.\n"
    )

    # subsystems ordered by size (largest first), like a table of contents
    for prefix in sorted(groups, key=lambda p: (-len(groups[p]), p)):
        rows = sorted(groups[prefix], key=lambda r: r[1])
        top = max((len(callees.get(n, ())) for n, _, _ in rows), default=0)
        out.append(f"\n## {prefix}  ({len(rows)} funcs, top out-degree {top})\n")
        out.append("| function | addr | size | calls |")
        out.append("|---|---|---|---|")
        for name, vram, size in rows:
            star = "*" if name in defined else " "
            calls = len(callees.get(name, ()))
            out.append(f"| `{name}` | 0x{vram:08X}{star} | 0x{size:X} | {calls} |")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
